### ISSUE TITLE
HTTPS Imgur Links

### ISSUE THREAD

**Issue by anoadragon453** [meditonsin/NightMirrorMoon#3]
I noticed all the imgur links provided use HTTP. Would there be any harm in having them default to HTTPS? Encrypted pone is best pone?

Great bot by the way!

**Comment by meditonsin** [comment]
Sorry for taking to long to react to this. I barely look at this Github account at the moment.

Should be fixed (along with all other instances that still used http instead of https) by c3fed6be2a4e2de14a1b92941f85601be82631b6.

**Comment by anoadragon453** [comment]
Cool, thanks.
